org:
  jboss:
    logging:
      provider: slf4j

server:
  port: 8090

#Database Configuration
db:
  driver: org.h2.Driver
  url: jdbc:h2:mem:datajpa
  username: sa
  password:

#Hibernate Configuration
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  ejb:
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  hbm2ddl:
    auto: create-drop
  show_sql: false
  format_sql: true

jdbc:
  connection:
    pool:
      size: 5

logging:
  level:
    ROOT: DEBUG
    com.rxonda: DEBUG
    reactor.ipc.netty: ERROR
    io.netty: ERROR
    org.springframework.web: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    com.zaxxer.hikari: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%-5level] [%t] %logger{36} - %msg%n"
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file: application.log
